/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Show;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author doriane kaffo 
 */
public class DialogUpdateAnimation extends javax.swing.JPanel {

    /**
     * Creates new form DialogUpdateAnimation
     */
    public DialogUpdateAnimation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameAnimation = new javax.swing.JLabel();
        animaux = new javax.swing.JComboBox();
        AnimauxAll = new javax.swing.JComboBox();
        addAnimal = new javax.swing.JToggleButton();
        removeAnimal = new javax.swing.JToggleButton();
        removePerson = new javax.swing.JToggleButton();
        persons = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        addPerson = new javax.swing.JToggleButton();
        personAll = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        update = new javax.swing.JToggleButton();
        dateAnimation = new javax.swing.JTextField();
        delete = new javax.swing.JToggleButton();

        jLabel1.setText("NOM DE L'ANIMATION : ");

        jLabel3.setText("Les Animaux : ");

        nameAnimation.setText("...");

        animaux.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AnimauxAll.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addAnimal.setText("Ajouter Animal");

        removeAnimal.setText("Enlever");
        removeAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAnimalActionPerformed(evt);
            }
        });

        removePerson.setText("Enlever");

        persons.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addPerson.setText("Ajouter Intervenant");

        personAll.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        personAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personAllActionPerformed(evt);
            }
        });

        jLabel4.setText("Les Intervenants : ");

        jLabel5.setText("La date : ");

        update.setText("Modifier");

        delete.setText("Supprimer");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(nameAnimation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(animaux, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(persons, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(personAll, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(addPerson)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(removePerson))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(AnimauxAll, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(addAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(removeAnimal)))
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(update)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(delete))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(71, 71, 71)
                                    .addComponent(dateAnimation, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameAnimation))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(animaux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAnimal)
                    .addComponent(AnimauxAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeAnimal))
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(persons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPerson)
                    .addComponent(removePerson))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(dateAnimation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update)
                    .addComponent(delete))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void removeAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeAnimalActionPerformed

    private void personAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personAllActionPerformed

    public JComboBox getAnimaux() {
        return animaux;
    }

    public JComboBox getAnimauxAll() {
        return AnimauxAll;
    }

    public void setAnimauxAll(JComboBox AnimauxAll) {
        this.AnimauxAll = AnimauxAll;
    }

    public JComboBox getPersonAll() {
        return personAll;
    }

    public void setPersonAll(JComboBox personAll) {
        this.personAll = personAll;
    }

    public void setAnimaux(JComboBox animaux) {
        this.animaux = animaux;
    }

    public JComboBox getPersons() {
        return persons;
    }

    public void setPersons(JComboBox persons) {
        this.persons = persons;
    }

    public JToggleButton getAddAnimal() {
        return addAnimal;
    }

    public void setAddAnimal(JToggleButton addAnimal) {
        this.addAnimal = addAnimal;
    }

    public JToggleButton getAddPerson() {
        return addPerson;
    }

    public void setAddPerson(JToggleButton addPerson) {
        this.addPerson = addPerson;
    }

    public JTextField getDateAnimation() {
        return dateAnimation;
    }

    public void setDateAnimation(JTextField dateAnimation) {
        this.dateAnimation = dateAnimation;
    }

    public JToggleButton getDelete() {
        return delete;
    }

    public void setDelete(JToggleButton delete) {
        this.delete = delete;
    }

    public JComboBox getjComboBox1() {
        return animaux;
    }

    public void setjComboBox1(JComboBox jComboBox1) {
        this.animaux = jComboBox1;
    }

    public JComboBox getjComboBox2() {
        return persons;
    }

    public void setjComboBox2(JComboBox jComboBox2) {
        this.persons = jComboBox2;
    }

    public JComboBox getjComboBox3() {
        return AnimauxAll;
    }

    public void setjComboBox3(JComboBox jComboBox3) {
        this.AnimauxAll = jComboBox3;
    }

    public JComboBox getjComboBox4() {
        return personAll;
    }

    public void setjComboBox4(JComboBox jComboBox4) {
        this.personAll = jComboBox4;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JLabel getNameAnimation() {
        return nameAnimation;
    }

    public void setNameAnimation(JLabel nameAnimation) {
        this.nameAnimation = nameAnimation;
    }

    public JToggleButton getRemoveAnimal() {
        return removeAnimal;
    }

    public void setRemoveAnimal(JToggleButton removeAnimal) {
        this.removeAnimal = removeAnimal;
    }

    public JToggleButton getRemovePerson() {
        return removePerson;
    }

    public void setRemovePerson(JToggleButton removePerson) {
        this.removePerson = removePerson;
    }

    public JToggleButton getUpdate() {
        return update;
    }

    public void setUpdate(JToggleButton update) {
        this.update = update;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AnimauxAll;
    private javax.swing.JToggleButton addAnimal;
    private javax.swing.JToggleButton addPerson;
    private javax.swing.JComboBox animaux;
    private javax.swing.JTextField dateAnimation;
    private javax.swing.JToggleButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameAnimation;
    private javax.swing.JComboBox personAll;
    private javax.swing.JComboBox persons;
    private javax.swing.JToggleButton removeAnimal;
    private javax.swing.JToggleButton removePerson;
    private javax.swing.JToggleButton update;
    // End of variables declaration//GEN-END:variables
}
