package View.Show;

import javax.swing.*;

    /**
     *
     * Cette classe contient le template du JPanel qui permet ENREGISTRER POUR LE FIRST FOIS
     *
     * @author doriane kaffo
     *
     * @version 1.0
     *
     * @date    30/05/2017..(Création)
     * @date    29/05/2017 (Finalisation v1.0)
     *
     */
    public class InitEvent extends javax.swing.JPanel {

        /**
         * Creates new form InitEvent
         */
        public InitEvent() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

            jLabel1e = new javax.swing.JLabel();
            jPanel1 = new SlideJPanel();
            jLabel2 = new javax.swing.JLabel();
            add = new javax.swing.JButton();
            jTextField1 = new javax.swing.JTextField();

            jLabel1e.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
            jLabel1e.setText("ZOO MANAGER");

            jPanel1.setBackground(new java.awt.Color(20, 20, 20));

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGap(0, 370, Short.MAX_VALUE)
            );
            jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGap(0, 0, Short.MAX_VALUE)
            );

            jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel2.setText("AJOUTEZ VOTRE PREMIER TYPE");

            add.setText("Ajouter");


            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(109, 109, 109)
                                                    .addComponent(jLabel1e))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(148, 148, 148)
                                                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(37, 37, 37)
                                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(56, 56, 56)
                                                    .addComponent(jLabel2)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addContainerGap())
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1e)
                                    .addGap(40, 40, 40)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(37, 37, 37)
                                    .addComponent(add)
                                    .addGap(64, 64, 64))
            );
        }// </editor-fold>
    private javax.swing.JButton add;
    private javax.swing.JLabel jLabel1e;
    private javax.swing.JLabel jLabel2;
    private SlideJPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration

    public JButton getAdd() {
        return add;
    }

    public void setAdd(JButton add) {
        this.add = add;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField1 = jTextField1;
    }
}

